# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

use_frameworks!

target 'Leavingstone-weather-app' do

  # Pods for Leavingstone-weather-app
	pod 'R.swift'
	pod 'R.swift.Library'
	pod 'Alamofire', '~> 5.2'
	pod 'AlamofireImage', '~> 4.1'
	pod 'SDWebImage', '~> 5.0'
end

